name: m2-actions-sequra-core-test

on: [push]

jobs:
  magento2-build:
    runs-on: ubuntu-latest
    container: ubuntu
    name: 'm2 tests & build'
    services:
      mysql:
        image: docker://mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: magento
          MYSQL_DATABASE: magento
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      opensearch:
        image: ghcr.io/mad-i-t/magento-opensearch:2.5.0
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node" -e "plugins.security.disabled=true" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    
    steps:
      ### Download the third party code in custom dir###
      - uses: actions/checkout@v3
        with:
          path: Sequra_Core

      - name: 'install fresh magento repo'
        uses: MAD-I-T/magento-actions@v3.20
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'install-magento'
          magento_version: 2.4.6
          no_push: 1   ## add this arg to not push to the repo ideal for quick test on specific version

      - name: 'launch magento2 unit test'
        if: always()
        uses: MAD-I-T/magento-actions@v3.20
        env:
          COMPOSER_AUTH: ${{secrets.COMPOSER_AUTH}}
        with:
          process: 'unit-test'
          unit_test_config: 'dev/tests/unit/phpunit.xml.dist'
          unit_test_subset_path: '../Sequra_Core/'
          
      - name: 'phpstan'
        if: always()
        uses: MAD-I-T/magento-actions@v3.20
        with:
          process: 'phpstan'
          exec_path: '../Sequra_Core/'
          
      - name: 'mess detector'
        if: always()
        uses: MAD-I-T/magento-actions@v3.20
        with:
          process: 'mess-detector'
          md_src_path: '../Sequra_Core/'

      - name: 'Magento coding standard checking'
        if: always()
        uses: MAD-I-T/magento-actions@v3.20
        with:
          process: 'phpcs-test'
          extension: 'Sequra_Core'
          severity: 10
          standard: 'Magento2'

      